policy_name: "memA-the-grid-fragmentation"
memcached:
  node: "node-b-4core"
  cores: "0"
  threads: 1
jobs:
  # --- NODE A ---
  freqmine:
    node: "node-a-8core"
    cores: "0-7"
    threads: 8
    after: "start"

  streamcluster:
    node: "node-a-8core"
    cores: "0-7"
    threads: 8
    after: "freqmine"
  radix:
    node: "node-a-8core"
    cores: "0-7"
    threads: 8
    after: "streamcluster"

  # --- NODE B ---
  # Pipe 1 (Cores 0-1)
  canneal:
    node: "node-b-4core"
    cores: "1"
    threads: 1
    after: "start"
    
  # Pipe 2 (Core 2)
  barnes:
    node: "node-b-4core"
    cores: "2"
    threads: 1
    after: "start"

    
  # Pipe 3 (Core 3)
  vips:
    node: "node-b-4core"
    cores: "3"
    threads: 1
    after: "start"


        #canneal FINISHES AFTER VIPS BUT BEFORE barnes
  blackscholes:
    node: "node-b-4core"
    cores: "3"
    threads: 1
    after: "vips"