apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-vips-2026-04-27-02h17m17s
  labels:
    cca-project-managed: "true"
    cca-project-experiment: "part3-handcrafted"
    cca-project-run-id: "2026-04-27-02h17m17s"
    cca-project-job-id: "vips"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        cca-project-managed: "true"
        cca-project-experiment: "part3-handcrafted"
        cca-project-run-id: "2026-04-27-02h17m17s"
        cca-project-job-id: "vips"
    spec:
      containers:
      - image: anakli/cca:parsec_vips
        name: parsec-vips
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 1-3 ./run -a run -S parsec -p vips -i native -n 3"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"
