apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-streamcluster-2026-05-10-02h59m16s
  labels:
    cca-project-managed: "true"
    cca-project-experiment: "part3-PartB"
    cca-project-run-id: "2026-05-10-02h59m16s"
    cca-project-job-id: "streamcluster"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        cca-project-managed: "true"
        cca-project-experiment: "part3-PartB"
        cca-project-run-id: "2026-05-10-02h59m16s"
        cca-project-job-id: "streamcluster"
    spec:
      containers:
      - image: anakli/cca:parsec_streamcluster
        name: parsec-streamcluster
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 4-7 ./run -a run -S parsec -p streamcluster -i native -n 4"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-a-8core"
