apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-canneal-2026-04-27-06h28m15s
  labels:
    cca-project-managed: "true"
    cca-project-experiment: "part3-handcrafted"
    cca-project-run-id: "2026-04-27-06h28m15s"
    cca-project-job-id: "canneal"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        cca-project-managed: "true"
        cca-project-experiment: "part3-handcrafted"
        cca-project-run-id: "2026-04-27-06h28m15s"
        cca-project-job-id: "canneal"
    spec:
      containers:
      - image: anakli/cca:parsec_canneal
        name: parsec-canneal
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0-1 ./run -a run -S parsec -p canneal -i native -n 2"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"
