apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-blackscholes-20260423t030618z
  labels:
    cca-project-managed: "true"
    cca-project-experiment: "part3-handcrafted"
    cca-project-run-id: "20260423t030618z"
    cca-project-job-id: "blackscholes"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        cca-project-managed: "true"
        cca-project-experiment: "part3-handcrafted"
        cca-project-run-id: "20260423t030618z"
        cca-project-job-id: "blackscholes"
    spec:
      containers:
      - image: anakli/cca:parsec_blackscholes
        name: parsec-blackscholes
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 1-3 ./run -a run -S parsec -p blackscholes -i native -n 3"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"
