apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-streamcluster-20260423t030618z
  labels:
    cca-project-managed: "true"
    cca-project-experiment: "part3-handcrafted"
    cca-project-run-id: "20260423t030618z"
    cca-project-job-id: "streamcluster"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        cca-project-managed: "true"
        cca-project-experiment: "part3-handcrafted"
        cca-project-run-id: "20260423t030618z"
        cca-project-job-id: "streamcluster"
    spec:
      containers:
      - image: anakli/cca:parsec_streamcluster
        name: parsec-streamcluster
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0-7 ./run -a run -S parsec -p streamcluster -i native -n 8"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-a-8core"
