apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-barnes-2026-04-27-07h08m04s
  labels:
    cca-project-managed: "true"
    cca-project-experiment: "part3-handcrafted"
    cca-project-run-id: "2026-04-27-07h08m04s"
    cca-project-job-id: "barnes"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        cca-project-managed: "true"
        cca-project-experiment: "part3-handcrafted"
        cca-project-run-id: "2026-04-27-07h08m04s"
        cca-project-job-id: "barnes"
    spec:
      containers:
      - image: anakli/cca:splash2x_barnes
        name: parsec-barnes
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 4-7 ./run -a run -S splash2x -p barnes -i native -n 4"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-a-8core"
