apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-vips-2026-04-27-06h56m54s
  labels:
    cca-project-managed: "true"
    cca-project-experiment: "part3-handcrafted"
    cca-project-run-id: "2026-04-27-06h56m54s"
    cca-project-job-id: "vips"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        cca-project-managed: "true"
        cca-project-experiment: "part3-handcrafted"
        cca-project-run-id: "2026-04-27-06h56m54s"
        cca-project-job-id: "vips"
    spec:
      containers:
      - image: anakli/cca:parsec_vips
        name: parsec-vips
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 4-7 ./run -a run -S parsec -p vips -i native -n 4"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-a-8core"
