apiVersion: v1
kind: Pod
metadata:
  name: memcached-server-2026-05-05-19h16m08s
  labels:
    cca-project-managed: "true"
    cca-project-experiment: "part3-OPENEVOLVE"
    cca-project-run-id: "2026-05-05-19h16m08s"
    cca-project-role: "memcached"
spec:
  containers:
  - image: anakli/memcached:t1
    name: memcached
    imagePullPolicy: Always
    command: ["/bin/sh"]
    args: ["-c", "taskset -c 0 ./memcached -t 1 -u memcache"]
  nodeSelector:
    cca-project-nodetype: "node-b-4core"
